name: dart_sqlite3
version: 0.3.0
description: >-
  Sqlite3 wrapper. Demo for dart:ffi.

homepage: https://github.com/bsjung/dart_sqlite3

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
dev_dependencies:

  test: ^1.5.3
